language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
env:
  - DB=mysql
install:
  - composer self-update
  - composer install
  - phpenv rehash
before_script:
   - phpenv config-add etc/myconfig.ini
   - php -S localhost:8000 src/public/index.php

